name: vulnerability scan workflow

on: push

jobs:
    meterian_scan:
        name: Meterian client scan
        runs-on: ubuntu-latest
        steps: 
          - name: Checkout
            uses: actions/checkout@v3
          - name: Scan project with the Meterian client
            uses: MeterianHQ/meterian-github-action@v1.0.17
            env:
                METERIAN_API_TOKEN: ${{ secrets.METERIAN_API_TOKEN }}
                GITHUB_TOKEN: ${{ github.token }}
            with:
                cli_args: "" #[ Meterian CLI Options ]
                # Autofix specific github action input variables 
                # More on autofix here:
                # https://github.com/MeterianHQ/meterian-github-action?tab=readme-ov-file#autofix-workflow
                autofix_security: safe
                autofix_stability: safe
                autofix_with_pr: true
